### ISSUE TITLE
UnifiedNlp disapperars after "freezing" by Titanium Backup

### ISSUE THREAD

**Issue by herrdeh** [microg/android_packages_apps_UnifiedNlp#44]
Unluckily, occasionally I need play services for certain apps. So I freeze UnifiedNlp in titBackup, unfreeze play services and use my app.

Unluckily, after frezzing play services, UnifiedNlp is disappeared from my system. Cannot be found in TitBack - can not even be reinstalled via Fdroid (you are trying to install a prior version...).

Downloading the apk and reinstalling that helped in the end - but it would be nice being able to switch back and forward between play services and U-Nlp.

**Comment by IzzySoft** [comment]
If you have ADB available: could you see if it's possible to "unfreeze" it using `adb shell "pm enable com.microg.nlp"`? If so, a work-around could be putting that into a little shell script to execute e.g. via Tasker or some other tool which can provide a "widget" for that – or, in the worst case, just from a terminal app.

If above command fails, also try manually:

~~~
PC> adb shell
Droid $ su
Droid # pm enable com.microg.nlp
~~~

in my experience, it sometimes requires root to do that.

**Comment by breversa** [comment]
Similar issue here :
µg UnifiedNlp (GApps version from F-Droid) launcher randomly disappears some seconds/minute after install ! It still appears in the installed apps list, but there's no way to launch it and set it up.
(If I open it quickly after install, I'm able to set up parameters

**Comment by mar-v-in** [comment]
There is a typo: it should be `org.microg.nlp`

**Comment by breversa** [comment]
Oh… my bad. I did not notice that sometimes I spelt wrong and sometimes right. So just to sum up what I actually did :

`root@maguro:/ # pm enable com.microg.nlp
Error: java.lang.IllegalArgumentException: Unknown package: com.microg.nlp`
(That's normal)

`root@maguro:/ # pm enable org.microg.nlp
Package org.microg.nlp new state: enabled`
… but still no launcher

Any other idea ?

**Comment by mar-v-in** [comment]
Sorry I did not follow through the entire thread. As you are using the Xposed version, the UnifiedNlp settings should pop up in System Settings > Location.

**Comment by breversa** [comment]
Catlog filtered on microg :

```
06-13 19:47:21.913 E/ActivityManager(1428):   0% 2478/org.microg.nlp.backend.ichnaea: 0% user + 0% kernel / faults: 58 minor
06-13 22:44:30.293 E/ActivityManager(1428):   0.5% 1886/org.microg.nlp: 0.1% user + 0.4% kernel / faults: 1122 minor 309 major
06-13 22:44:30.293 E/ActivityManager(1428):   0.1% 2478/org.microg.nlp.backend.ichnaea: 0.1% user + 0% kernel / faults: 63 minor
06-13 22:45:41.554 I/ActivityManager(1428): Force stopping org.microg.nlp appid=10181 user=0: pkg changed
06-13 22:45:41.562 I/ActivityManager(1428): Killing 1886:org.microg.nlp/u0a181 (adj 1): stop org.microg.nlp
06-13 22:45:41.688 W/ActivityManager(1428): Scheduling restart of crashed service org.microg.nlp/.location.LocationServiceV2 in 1000ms
06-13 22:45:41.688 W/ActivityManager(1428): Scheduling restart of crashed service org.microg.nlp/.geocode.GeocodeServiceV1 in 11000ms
06-13 22:45:41.739 I/ActivityManager(1428):   Force stopping service ServiceRecord{a5c8cd7 u0 org.microg.nlp/.geocode.GeocodeServiceV1}
06-13 22:45:41.739 I/ActivityManager(1428):   Force stopping service ServiceRecord{30563fcf u0 org.microg.nlp/.location.LocationServiceV2}
06-13 22:45:41.800 W/ActivityManager(1428): Spurious death for ProcessRecord{12a1ceef 0:org.microg.nlp/u0a181}, curProc for 1886: null
06-13 22:45:42.207 D/BackupManagerService(1428): Received broadcast Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:org.microg.nlp flg=0x4000010 (has extras) }
06-13 22:45:46.664 I/ActivityManager(1428): Start proc 28977:org.microg.nlp/u0a181 for broadcast org.microg.nlp/.PackageReceiver
06-13 22:45:48.131 E/ActivityThread(28977): Service org.microg.nlp.geocode.GeocodeServiceV1 has leaked ServiceConnection org.microg.nlp.geocode.BackendHelper@30597ca4 that was originally bound here
06-13 22:45:48.131 E/ActivityThread(28977): android.app.ServiceConnectionLeaked: Service org.microg.nlp.geocode.GeocodeServiceV1 has leaked ServiceConnection org.microg.nlp.geocode.BackendHelper@30597ca4 that was originally bound here
06-13 22:45:48.131 E/ActivityThread(28977): 	at org.microg.nlp.AbstractBackendHelper.bind(AbstractBackendHelper.java:94)
06-13 22:45:48.131 E/ActivityThread(28977): 	at org.microg.nlp.geocode.BackendFuser.bind(BackendFuser.java:41)
06-13 22:45:48.131 E/ActivityThread(28977): 	at org.microg.nlp.geocode.GeocodeProviderV1.reload(GeocodeProviderV1.java:69)
06-13 22:45:48.131 E/ActivityThread(28977): 	at org.microg.nlp.geocode.AbstractGeocodeService.onHandleIntent(AbstractGeocodeService.java:47)
06-13 22:45:51.022 E/ActivityThread(28977): Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@24ec3a0d that was originally bound here
06-13 22:45:51.022 E/ActivityThread(28977): android.app.ServiceConnectionLeaked: Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@24ec3a0d that was originally bound here
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.AbstractBackendHelper.bind(AbstractBackendHelper.java:94)
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.location.BackendFuser.bind(BackendFuser.java:75)
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.enable(ThreadHelper.java:66)
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.reload(ThreadHelper.java:39)
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.location.LocationProviderV2.reload(LocationProviderV2.java:59)
06-13 22:45:51.022 E/ActivityThread(28977): 	at org.microg.nlp.location.AbstractLocationService.onHandleIntent(AbstractLocationService.java:77)
06-13 22:45:51.202 E/ActivityThread(28977): Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@2552ddc2 that was originally bound here
06-13 22:45:51.202 E/ActivityThread(28977): android.app.ServiceConnectionLeaked: Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@2552ddc2 that was originally bound here
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.AbstractBackendHelper.bind(AbstractBackendHelper.java:94)
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.location.BackendFuser.bind(BackendFuser.java:75)
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.enable(ThreadHelper.java:66)
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.reload(ThreadHelper.java:39)
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.location.LocationProviderV2.reload(LocationProviderV2.java:59)
06-13 22:45:51.202 E/ActivityThread(28977): 	at org.microg.nlp.location.AbstractLocationService.onHandleIntent(AbstractLocationService.java:77)
06-13 22:45:51.222 E/ActivityThread(28977): Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@29e5b7d3 that was originally bound here
06-13 22:45:51.222 E/ActivityThread(28977): android.app.ServiceConnectionLeaked: Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@29e5b7d3 that was originally bound here
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.AbstractBackendHelper.bind(AbstractBackendHelper.java:94)
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.location.BackendFuser.bind(BackendFuser.java:75)
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.enable(ThreadHelper.java:66)
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.reload(ThreadHelper.java:39)
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.location.LocationProviderV2.reload(LocationProviderV2.java:59)
06-13 22:45:51.222 E/ActivityThread(28977): 	at org.microg.nlp.location.AbstractLocationService.onHandleIntent(AbstractLocationService.java:77)
06-13 22:45:51.228 E/ActivityThread(28977): Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@3fb45f37 that was originally bound here
06-13 22:45:51.228 E/ActivityThread(28977): android.app.ServiceConnectionLeaked: Service org.microg.nlp.location.LocationServiceV2 has leaked ServiceConnection org.microg.nlp.location.BackendHelper@3fb45f37 that was originally bound here
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.AbstractBackendHelper.bind(AbstractBackendHelper.java:94)
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.location.BackendFuser.bind(BackendFuser.java:75)
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.enable(ThreadHelper.java:66)
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.location.ThreadHelper.reload(ThreadHelper.java:39)
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.location.LocationProviderV2.reload(LocationProviderV2.java:59)
06-13 22:45:51.228 E/ActivityThread(28977): 	at org.microg.nlp.location.AbstractLocationService.onHandleIntent(AbstractLocationService.java:77)
06-13 22:48:07.031 I/ActivityManager(1428): Process org.microg.nlp.backend.ichnaea (pid 2478) has died
06-13 22:48:28.260 D/NlpPackageReceiver(28977): Intent received: Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.keramidas.TitaniumBackup flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:48:48.590 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:48:48.590 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:48:48.590 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.590 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.590 D/NlpLocBackendHelper(28977): Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GsmService_ }
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.close(LocationBackend.java:178)
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.close(BackendHelper.java:119)
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:66)
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.598 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.602 W/NlpLocBackendHelper(28977): java.lang.IllegalArgumentException: Service not registered: org.microg.nlp.location.BackendHelper@24ec3a0d
06-13 22:48:48.602 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:72)
06-13 22:48:48.602 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.602 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.602 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.603 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:48:48.603 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:48:48.603 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.603 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.603 D/NlpLocBackendHelper(28977): Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.wifi_backend cmp=org.fitchfamily.android.wifi_backend/.backend.BackendService_ }
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.close(LocationBackend.java:178)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.close(BackendHelper.java:119)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:66)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): java.lang.IllegalArgumentException: Service not registered: org.microg.nlp.location.BackendHelper@2552ddc2
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:72)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.607 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.608 D/NlpLocBackendHelper(28977): Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.microg.nlp.backend.ichnaea cmp=org.microg.nlp.backend.ichnaea/.BackendService }
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.close(LocationBackend.java:178)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.close(BackendHelper.java:119)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:66)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.608 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.611 W/NlpLocBackendHelper(28977): java.lang.IllegalArgumentException: Service not registered: org.microg.nlp.location.BackendHelper@29e5b7d3
06-13 22:48:48.611 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.AbstractBackendHelper.unbind(AbstractBackendHelper.java:72)
06-13 22:48:48.611 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:78)
06-13 22:48:48.611 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:48:48.611 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:48:48.656 V/NlpLocationBackendFuser(28977): location=Location[network 42,000000,42,000000 acc=10 et=+7h47m14s787ms {Bundle[{noGPSLocation=Location[network 42,000000,42,000000 acc=10 et=+7h47m14s787ms], SERVICE_BACKEND_PROVIDER=DummyBackend, SERVICE_BACKEND_COMPONENT=de.r3w6.xposedunifiednlp/.DummyBackend, OTHER_BACKEND_RESULTS=[Location[network 48,601952,7,745967 acc=1102 et=+7h46m14s990ms {Bundle[{noGPSLocation=Location[network 48,601952,7,745967 acc=1102 et=+7h46m14s990ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}], Location[network 48,601854,7,745922 acc=1000 et=+7h44m16s969ms {Bundle[{noGPSLocation=Location[network 48,601854,7,745922 acc=1000 et=+7h44m16s969ms], SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]]}]}]
06-13 22:49:26.956 E/Pm      (29888): java.lang.IllegalArgumentException: Unknown package: com.microg.nlp
06-13 22:49:49.072 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:49:49.072 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:49:49.072 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:49:49.072 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
06-13 22:49:49.073 W/NlpLocBackendHelper(28977): 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
06-13 22:49:49.079 V/NlpLocationBackendFuser(28977): location=Location[network 42,000000,42,000000 acc=10 et=+7h48m14s674ms {Bundle[{noGPSLocation=Location[network 42,000000,42,000000 acc=10 et=+7h48m14s674ms], SERVICE_BACKEND_PROVIDER=DummyBackend, SERVICE_BACKEND_COMPONENT=de.r3w6.xposedunifiednlp/.DummyBackend, OTHER_BACKEND_RESULTS=[Location[network 48,601952,7,745967 acc=1102 et=+7h46m14s990ms {Bundle[{noGPSLocation=Location[network 48,601952,7,745967 acc=1102 et=+7h46m14s990ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}], Location[network 48,601854,7,745922 acc=1000 et=+7h44m16s969ms {Bundle[{noGPSLocation=Location[network 48,601854,7,745922 acc=1000 et=+7h44m16s969ms], SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]]}]}]
06-13 22:49:51.827 D/NlpPackageReceiver(28977): Intent received: Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.imdb.mobile flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:49:59.560 I/ActivityManager(1428): Killing 2035:org.microg.nlp.backend.nominatim/u0a75 (adj 15): empty #17
06-13 22:50:13.442 D/NlpPackageReceiver(28977): Intent received: Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.imdb.mobile flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:50:42.054 I/ActivityManager(1428): Process org.microg.nlp (pid 28977) has died
06-13 22:51:21.913 I/ActivityManager(1428): Start proc 30823:org.microg.nlp/u0a181 for broadcast org.microg.nlp/.PackageReceiver
06-13 22:51:23.017 D/NlpPackageReceiver(30823): Intent received: Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.mkrtchyan.recoverytools flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:51:48.979 D/NlpPackageReceiver(30823): Intent received: Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:de.mkrtchyan.recoverytools flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:52:09.867 I/ActivityManager(1428): Process org.microg.nlp (pid 30823) has died
06-13 22:53:08.870 I/ActivityManager(1428): Start proc 31987:org.microg.nlp/u0a181 for broadcast org.microg.nlp/.PackageReceiver
06-13 22:53:10.824 D/NlpPackageReceiver(31987): Intent received: Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:ccc71.bmw flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:53:33.690 D/NlpPackageReceiver(31987): Intent received: Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:ccc71.bmw flg=0x4000010 cmp=org.microg.nlp/.PackageReceiver (has extras) }
06-13 22:53:54.674 I/ActivityManager(1428): Process org.microg.nlp (pid 31987) has died
```

**Comment by breversa** [comment]
Holy sh*t ! I NEVER noticed that ! THANK YOU @mar-v-in , you saved my day ! :D :D :D
