### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by vanitasvitae** [microg/android_packages_apps_UnifiedNlp#63]
Hi!
I found this error in my logcat several times (Im on CopperheadOS):
```
02-17 18:59:35.308 17609 17609 I SignalStrengthTracker: Removing old signal strength entries from DB.
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: Exception
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at android.os.Parcel.readException(Parcel.java:1620)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at android.os.Parcel.readException(Parcel.java:1573)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1281)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at com.android.location.provider.LocationProviderBase.reportLocation(LocationProviderBase.java:136)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at org.microg.nlp.location.BackendFuser.updateLocation(BackendFuser.java:101)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:86)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:77)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-17 18:59:35.767 24807 25051 E NlpLocationProvider: 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by mar-v-in** [comment]
CopperheadOS does not support network location, please file a bug on them. For technical details, see [this comment regarding Fairphone OSOS 2](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/55#issuecomment-174587233).

**Comment by vanitasvitae** [comment]
Ok thanks :)

**Comment by calebj** [comment]
Future internet travelers: I had this issue on my H830 running Resurrection Remix, based on Lineage 14.1 (7.1 nougat).

I'm not using UnifiedNlp by itself, but rather GMSCore v0.2.4. To fix it, I had to install it as a system app as per the readme. I'm only posting this here to link this exception with the fix.

**Comment by ale5000-git** [comment]
@calebj: It is already duscussed [here](https://github.com/microg/android_packages_apps_GmsCore/issues/284).

**Comment by calebj** [comment]
I see. All I had to go on was that exception, though. There was no reference until now.
