### ISSUE TITLE
Gsm location doesn't work

### ISSUE THREAD

**Issue by Paviluf** [microg/android_packages_apps_UnifiedNlp#80]
I'm using the mozilla location backend. The location work on Wifi and GPS but not with the Gsm (2G, 3G) network.

UnifiedNlp 1.6.2 dirty (fdroid)

Android 4.4 (CM 11)
Motorola Razr i (x86)

Thanks

**Comment by mar-v-in** [comment]
@n76 CellBackendHelper (provided through UnifiedNlpApi) already has support for CellInfo(GCM,CDMA,WCDMA,LTE), NeighboringCellInfo(GSM) and CellLocation(GCM,CDMA). Is there anything else that should be covered?

@Paviluf Can you check whether, and if how many, GSM cells are shown in SatStat (third tab) on your device?

**Comment by n76** [comment]
Looking at the current version of CellBackendHelper, it looks like it properly falls back to CellLocation. But for some reason it is not working on my Maguro running ZMOD 5.1.1. I guess I should build a version of one of your backends that use this with some logging or debug enabled to see what is going on.

**Comment by Paviluf** [comment]
@mar-v-in here is what SatStat find

![screenshot_2016-03-25-17-09-21](https://cloud.githubusercontent.com/assets/17159065/14048190/f9a48be0-f2ac-11e5-8aeb-ced3890b9ef8.png)
![screenshot_2016-03-25-17-10-37](https://cloud.githubusercontent.com/assets/17159065/14048191/f9a713a6-f2ac-11e5-88d4-44e82a81262e.png)

**Comment by Paviluf** [comment]
@mar-v-in I guess you are very busy but does the infos I gave to you help ?
Do you need anything else ?
Thanks !

**Comment by mar-v-in** [comment]
@Paviluf You should be able to properly geolocate on both 2G and 3G with the data provided in the screenshot. Can you use logcat to investigate why the Mozilla plugin fails? Search for log output with tag "IchnaeaBackendService"

**Comment by Paviluf** [comment]
I made 2 logcats. The first one only in 2G and the second in Wifi + 2G :

**2G**
http://pastebin.com/L8vdrUKZ

**Wifi**
http://pastebin.com/bXku6T1c

In 2G only there is no "IchnaeaBackendService" entry !

In Wifi + 2G this is the "IchnaeaBackendService" entry :

```
04-03 12:45:48.676 D/IchnaeaBackendService(934): request: {"wifiAccessPoints":[{"signalStrength":-91,"channel":11,"frequency":2462,"macAddress":"88:9f:fa:01:2b:7b"},{"signalStrength":-73,"channel":6,"frequency":2437,"macAddress":"00:22:3f:18:a1:6f"}],"fallbacks":{"ipf":false,"lacf":true},"cellTowers":[]}

04-03 12:45:49.166 W/IchnaeaBackendService(934): Error: {"error":{"code":404,"message":"Not found","errors":[{"domain":"geolocation","message":"Not found","reason":"notFound"}]}}
04-03 12:45:49.176 W/IchnaeaBackendService(934): java.io.FileNotFoundException: https://location.services.mozilla.com/v1/geolocate?key=068ab754-c06b-473d-a1e5-60e7b1a2eb77
04-03 12:45:49.176 W/IchnaeaBackendService(934): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
04-03 12:45:49.176 W/IchnaeaBackendService(934): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
04-03 12:45:49.176 W/IchnaeaBackendService(934): 	at org.microg.nlp.backend.ichnaea.BackendService$1.run(BackendService.java:141)
04-03 12:45:49.176 W/IchnaeaBackendService(934): 	at java.lang.Thread.run(Thread.java:841)

04-03 12:45:55.706 D/IchnaeaBackendService(934): request: {"wifiAccessPoints":[{"signalStrength":-88,"channel":1,"frequency":2412,"macAddress":"00:37:b7:0a:87:76"},{"signalStrength":-79,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:52"},{"signalStrength":-85,"channel":11,"frequency":2462,"macAddress":"88:9f:fa:01:2b:7b"},{"signalStrength":-82,"channel":6,"frequency":2437,"macAddress":"b8:26:6c:c8:16:ea"},{"signalStrength":-78,"channel":6,"frequency":2437,"macAddress":"00:22:3f:18:a1:6f"},{"signalStrength":-88,"channel":11,"frequency":2462,"macAddress":"f0:92:1c:a6:60:6b"},{"signalStrength":-90,"channel":6,"frequency":2437,"macAddress":"00:19:70:69:b3:78"},{"signalStrength":-79,"channel":1,"frequency":2412,"macAddress":"e0:ca:94:ac:2e:c3"},{"signalStrength":-79,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:50"},{"signalStrength":-78,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:53"},{"signalStrength":-86,"channel":1,"frequency":2412,"macAddress":"d0:ae:ec:28:0c:24"},{"signalStrength":-81,"channel":1,"frequency":2412,"macAddress":"54:64:d9:49:bd:9e"}],"fallbacks":{"ipf":false,"lacf":true},"cellTowers":[]}

04-03 12:45:55.826 D/IchnaeaBackendService(934): response: {"location": {"lat": 44.86469, "lng": -0.60919}, "accuracy": 131.8230805}
04-03 12:45:55.826 D/IchnaeaBackendService(934): reporting: Location[ichnaea 44,864690,-0,609190 acc=132 t=?!? et=?!?]

04-03 12:46:03.066 D/IchnaeaBackendService(934): request: {"wifiAccessPoints":[{"signalStrength":-80,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:50"},{"signalStrength":-83,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:51"},{"signalStrength":-77,"channel":6,"frequency":2437,"macAddress":"00:22:3f:18:a1:6f"},{"signalStrength":-82,"channel":6,"frequency":2437,"macAddress":"b8:26:6c:c8:16:ea"},{"signalStrength":-81,"channel":1,"frequency":2412,"macAddress":"54:64:d9:49:bd:9e"},{"signalStrength":-83,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:52"},{"signalStrength":-88,"channel":1,"frequency":2412,"macAddress":"00:37:b7:0a:87:76"},{"signalStrength":-90,"channel":6,"frequency":2437,"macAddress":"00:19:70:69:b3:78"},{"signalStrength":-79,"channel":7,"frequency":2442,"macAddress":"6a:12:f8:a9:b9:53"},{"signalStrength":-87,"channel":1,"frequency":2412,"macAddress":"e0:ca:94:ac:2e:c3"},{"signalStrength":-84,"channel":11,"frequency":2462,"macAddress":"88:9f:fa:01:2b:7b"},{"signalStrength":-88,"channel":11,"frequency":2462,"macAddress":"f0:92:1c:a6:60:6b"},{"signalStrength":-92,"channel":1,"frequency":2412,"macAddress":"d0:ae:ec:28:0c:24"}],"fallbacks":{"ipf":false,"lacf":true},"cellTowers":[]}
04-03 12:46:03.156 I/Timeline(517): Timeline: Activity_windows_visible id: ActivityRecord{21c264f8 u0 com.nolanlawson.logcat/.LogcatActivity t6} time:449408
04-03 12:46:03.186 D/IchnaeaBackendService(934): response: {"location": {"lat": 44.8647108, "lng": -0.6091771}, "accuracy": 133.3812471}
04-03 12:46:03.186 D/IchnaeaBackendService(934): reporting: Location[ichnaea 44,864711,-0,609177 acc=133 t=?!? et=?!?]
```

**Comment by Paviluf** [comment]
@mar-v-in I saw that you have worked on increased cell location support and with MozillaNlpBackend v. 1.3.2 it seems to work now ! Thanks !

**Comment by Paviluf** [comment]
@mar-v-in Since it work now (thank you again !) I will be pleased to close this issue but I don't know if you still need to make more changes to complete the fix ?

**Comment by mar-v-in** [comment]
I guess the work-around with latest version is working properly on all devices. Maybe @n76 can verify this?

**Comment by n76** [comment]
Just tried v1.3.2 from F-Droid (updated 8Apr so I think it has your latest changes) and from logcat it is getting a cell/mobile tower in addition to the WiFi/WLAN, so it appears to be working for me. My Galaxy Nexus (maguro) has never shown more than one cell/mobile regardless of version of Android, so I would not expect to see more than one tower.

As far as I can tell, this is fixed.

**Comment by mar-v-in** [comment]
Great.
