### ISSUE TITLE
WhatsApp crashes when opening chat with Location

### ISSUE THREAD

**Issue by Nutomic** [microg/android_packages_apps_UnifiedNlp#99]
When someone sends a location in WhatsApp, it is displayed as a small preview of the map. This works fine in 0.2.4-7-g5a0c235, but causes the following crash in 0.2.4-8-g2fa70c1 (both versions from the microg F-Droid repo). This was on an LG G4.

```
09-13 11:52:12.717 32184 32184 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.gms-1/lib/arm64/libvtm-jni.so" is 64-bit instead of 32-bit
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at java.lang.Runtime.loadLibrary(Runtime.java:372)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1076)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.oscim.android.MapView.<clinit>(MapView.java:52)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.BackendMap.<init>(BackendMap.java:70)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.GoogleMapImpl.<init>(GoogleMapImpl.java:136)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.GoogleMapImpl.create(GoogleMapImpl.java:149)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.MapViewImpl.myMap(MapViewImpl.java:51)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.MapViewImpl.getView(MapViewImpl.java:107)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact(IMapViewDelegate.java:119)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at org.microg.gms.maps.MapViewImpl.onTransact(MapViewImpl.java:127)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at android.os.Binder.transact(Binder.java:387)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.a.o.f(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.n.a(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.a.d.b(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.a.c.a(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.p.e(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.p.a(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.a.b.a(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.a.b.a(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.whatsapp.rd.run(ConversationRowLocation.java:134)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-13 11:52:12.717 32184 32184 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Nutomic** [comment]
This was fixed some time ago by updating UnifiedNlp.
